### ISSUE TITLE
Panic while decoding extrinsic

### ISSUE THREAD

**Issue by amintalebi** [itering/substrate-api-rpc#10]
I have problems decoding the following extrinsic.

`0x2d028400d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d01608ecd57e5d9e7544157b8fe184a728324270e5c336b36ab5e43c037b9c8e86c1e3da0bd1e7cec93221f070288b993f75e584889b2a505d27f518b3328a7f885060000000600008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a4804`

This is the error trace:

```
panic: runtime error: index out of range [125] with length 3

goroutine 1 [running]:
github.com/itering/scale.go/types.(*Enum).Process(0xc00049a0b0)
        /Users/amin/go/pkg/mod/github.com/itering/scale.go@v1.1.35/types/types.go:320 +0x785
reflect.Value.call({0x13a9cc0, 0xc00049a0b0, 0x3}, {0x13c3527, 0x4}, {0x0, 0x0, 0x1465890})
        /usr/local/opt/go/libexec/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x13a9cc0, 0xc00049a0b0, 0x0}, {0x0, 0x0, 0x0})
        /usr/local/opt/go/libexec/src/reflect/value.go:339 +0xc5
github.com/itering/scale.go/types.(*ScaleDecoder).ProcessAndUpdateData(0xc000325e38, {0x13c7afc, 0x12})
        /Users/amin/go/pkg/mod/github.com/itering/scale.go@v1.1.35/types/base.go:140 +0x4b4
github.com/itering/scale%2ego.(*ExtrinsicDecoder).Process(0xc000325e38)
        /Users/amin/go/pkg/mod/github.com/itering/scale.go@v1.1.35/extrinsic.go:91 +0x411
main.main()
        /Users/amin/Development/amintalebi/substrate-rpc-go/main.go:63 +0x685
```
And this the code:

```
instant := metadata.Process(runtimeraw)
m := types3.MetadataStruct(*instant)
e := scale.ExtrinsicDecoder{}
option := types3.ScaleDecoderOption{Metadata: &m, Spec: 0}
e.Init(types3.ScaleBytes{Data: util.HexToBytes(block.Block.Extrinsics[1])}, &option)
e.Process()
```

**Comment by freehere107** [comment]
@amintalebi Which block num?

**Comment by amintalebi** [comment]
It's from a block on my local node. It's a signed extrinsic.

**Comment by freehere107** [comment]
> It's from a block on my local node. It's a signed extrinsic.

Need to check the registered type
https://github.com/itering/scale.go/blob/master/extrinsic_test.go#L22
